services:
  - type: web
    name: ppc
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGIN
        sync: false
      - key: type
        sync: false
      - key: project_id
        sync: false
      - key: private_key_id
        sync: false
      - key: private_key
        sync: false
      - key: client_email
        sync: false
      - key: client_id
        sync: false
      - key: auth_uri
        sync: false
      - key: token_uri
        sync: false
      - key: auth_provider_x509_cert_url
        sync: false
      - key: client_x509_cert_url
        sync: false
      - key: universe_domain
        sync: false
